FROM node:alpine AS builder
WORKDIR /app
COPY . .

FROM nginx:alpine
COPY --from=builder /app/index.html /usr/share/nginx/html/index.html
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/404.html /usr/share/nginx/html/404.html
